#define DIV_CEIL(x, y) ((x % y) ? x / y + 1 : x / y)

#define DISPLAY_FRAME_WIDTH CONFIG_DISPLAY_FRAME_WIDTH
#define DISPLAY_FRAME_HEIGHT CONFIG_DISPLAY_FRAME_HEIGHT
#define DISPLAY_VIEWPORT_OFFSET_X CONFIG_DISPLAY_VIEWPORT_OFFSET_X
#define DISPLAY_VIEWPORT_OFFSET_Y CONFIG_DISPLAY_VIEWPORT_OFFSET_Y

#if defined(CONFIG_DISPLAY_HAS_BRIGHTNESS_CONTROL)
    #define DISPLAY_HAS_BRIGHTNESS_CONTROL 1
#else
    #define DISPLAY_HAS_BRIGHTNESS_CONTROL 0
#endif

#if defined(CONFIG_DISPLAY_TYPE_PIXEL)
    #define DISPLAY_TYPE "pixel"

    #define DISPLAY_FRAMEBUF_SIZE_1BPP (CONFIG_DISPLAY_FRAME_WIDTH * DIV_CEIL(CONFIG_DISPLAY_FRAME_HEIGHT, 8))
    #define DISPLAY_FRAMEBUF_SIZE_8BPP (CONFIG_DISPLAY_FRAME_WIDTH * CONFIG_DISPLAY_FRAME_HEIGHT)
    #define DISPLAY_FRAMEBUF_SIZE_24BPP (CONFIG_DISPLAY_FRAME_WIDTH * CONFIG_DISPLAY_FRAME_HEIGHT * 3)

    #if defined(CONFIG_DISPLAY_FRAME_TYPE_1BPP)
        #define DISPLAY_FRAME_TYPE "1bpp"
        #define DISPLAY_FRAMEBUF_SIZE DISPLAY_FRAMEBUF_SIZE_1BPP
        #define DISPLAY_FRAME_HEIGHT_BYTES DIV_CEIL(CONFIG_DISPLAY_FRAME_HEIGHT, 8)
        #define BUFFER_VAL(buf, x, y) ((buf[(x * DISPLAY_FRAME_HEIGHT_BYTES) + (y / 8)] >> (y % 8)) & 1)
    #elif defined(CONFIG_DISPLAY_FRAME_TYPE_8BPP)
        #define DISPLAY_FRAME_TYPE "8bpp"
        #define DISPLAY_FRAMEBUF_SIZE DISPLAY_FRAMEBUF_SIZE_8BPP
        #define DISPLAY_FRAME_HEIGHT_BYTES CONFIG_DISPLAY_FRAME_HEIGHT
    #elif defined(CONFIG_DISPLAY_FRAME_TYPE_24BPP)
        #define DISPLAY_FRAME_TYPE "24bpp"
        #define DISPLAY_FRAMEBUF_SIZE DISPLAY_FRAMEBUF_SIZE_24BPP
        #define DISPLAY_FRAME_HEIGHT_BYTES (CONFIG_DISPLAY_FRAME_HEIGHT * 3)
    #endif
#elif defined(CONFIG_DISPLAY_TYPE_CHARACTER)
    #define DISPLAY_TYPE "character"
    #define DISPLAY_FRAME_TYPE ""
    #define DISPLAY_CHARBUF_SIZE (CONFIG_DISPLAY_FRAME_WIDTH * CONFIG_DISPLAY_FRAME_HEIGHT)
    #define DISPLAY_FRAMEBUF_SIZE (DIV_CEIL(DISPLAY_CHARBUF_SIZE * CONFIG_DISPLAY_FRAMEBUF_BITS_PER_CHAR, 8))
#endif

#if defined(CONFIG_DISPLAY_DRIVER_FLIPDOT_LAWO_ALUMA)
    #define DISPLAY_DRIVER "flipdot_lawo_aluma"
#elif defined(CONFIG_DISPLAY_DRIVER_FLIPDOT_BROSE)
    #define DISPLAY_DRIVER "flipdot_brose"
#elif defined(CONFIG_DISPLAY_DRIVER_FLIPDOT_SAFLAP)
    #define DISPLAY_DRIVER "flipdot_saflap"
#elif defined(CONFIG_DISPLAY_DRIVER_LED_SHIFT_REGISTER)
    #define DISPLAY_DRIVER "led_shift_register"
#elif defined(CONFIG_DISPLAY_DRIVER_LED_SHIFT_REGISTER_I2S)
    #define DISPLAY_DRIVER "led_shift_register_i2s"
#elif defined(CONFIG_DISPLAY_DRIVER_LED_AESYS_I2S)
    #define DISPLAY_DRIVER "led_aesys_i2s"
#elif defined(CONFIG_DISPLAY_DRIVER_CHAR_SEG_LCD_SPI)
    #define DISPLAY_DRIVER "char_seg_lcd_spi"
#elif defined(CONFIG_DISPLAY_DRIVER_CHAR_16SEG_LED_SPI)
    #define DISPLAY_DRIVER "char_16seg_led_spi"
#endif